//Created by Petar Ostojic
//Wed Mar 18 00:18:37 2015
#ifndef GUIDEFINES_H
#define GUIDEFINES_H
#define GUI_WIDGET_NOT_DEFINED 0
#define GUI_WIDGET_CONTAINER 1
#define GUI_WIDGET_BUTTON 2
#define GUI_WIDGET_CHECKBOX 3
#define GUI_WIDGET_RADIO 4
#define GUI_WIDGET_LABEL 5
#define GUI_WIDGET_INPUT 6
#define GUI_WIDGET_COMBOBOX 7
#define GUI_WIDGET_HOR_SLIDER 8
#define GUI_WIDGET_VER_SLIDER 9
#define GUI_WIDGET_PICTUREBOX 10
#define GUI_WIDGET_LIST 11

//GUI widget event types
#define GUI_WIDGET_EVENT_NOTHING 0
#define GUI_WIDGET_EVENT_HANDLED 1

#endif